bank_names = {
    'Bradesco': {
        'Bradesco': r'bradesco',
        'Florida Bank': 'florida bank',
        'HSBC': 'hsbc',
        'BERJ': '(\sBERJ\s)|(banco do estado do rio de janeiro)',
        'IBI Mexico': r'(ibi mexico)|(banco ibi)',
        'Agora Corretora': 'agora corretora',
        'Banco BMC': 'banco bmc',
        'Banco do Estado do Ceara': r'banco do estado do ceara',
        'Banco do Estado do Maranhao': r'banco do estado do maranhao',
        'Banco Zogbi': r'Banco Zogbi',
        'BBVA': r'(banco bilbao vizcaya argentaria brasil)|(bbva)',
        'Banco Cidade': r'(banco cidade)|bancocidade',
        'Banco Espirito Santo': r'banco espirito santo',
        'Banco do Estado do Amazonas': r'banco do estado do amazonas',
        'Banco Mercantil de Sao Paulo': r'banco mercantil de sao paulo',
        'Banco Comercial de Minas Gerais': r'Banco Comercial de Minas Gerais',
        'Deutsche Bank': r'deutsche bank',
        'Banco Ford': r'(banco ford)|(ford leasing)',
        'Banque BANESPA International': r'Banque BANESPA International',
        'Banco Boavista Interatlantico': 'banco boavista interatlantico',
        'Banco das Nacoes': r'banco das nacoes',
        'baneb': r'(banco do estado da bahia)|(baneb)',
        'Banco Continental': r'Banco Continental',
        'Credireal': r'(Banco De Credito Real De Minas Gerais)|credireal',
        'Itabanco': 'itabanco',
        'Banco de Credito Nacional': r'banco de credito nacional',
        'Banco da Bahia': r'banco da bahia',
        'Banco Mineiro do Oeste': r'Banco Mineiro do Oeste',
        'Banco dos Importadores e Exportadores do Ceara': r'Banco dos Importadores e Exportadores do Ceara',
        'Banco de Credito Comercial': r'banco de credito comercial',
        'Banco Villarino': r'banco villarino',
        'Banco Agricola da Alta Mogiana': r'banco agricola da alta mogiana',
        'Banco Industria e Comercio de Santa Catarina': r'banco industria e comercio de santa catarina',
        'Banco Seguranca': r'banco seguranca',
        'Banco Porto Alegrense': r'Banco Porto Alegrense',
        'Banco Mercantil de Pernambuco': r'banco mercantil de pernambuco',
        'Banco Brasileiro de Sao Saulo': r'banco brasileiro de sao paulo',
        'Banco Correa Ribeiro': r'banco correa ribeiro',
        'Banco Brasileiro de Goias': r'banco brasileiro de goias',
        'Banco Popular do Brasil': r'banco popular do brasil',
        'Banco Nacional Interamericano': r'banco nacional interamericano',
        'Banco Mobilizador de Credito': r'banco mobilizador de credito',
        'Banco Excel': r'banco excel',
        'Kirton Nank': r'kirton bank',
        'Credit de France': r'credit de france',
        'Bamerindus': r'(bamerindus)|(Banco Mercantil e Industrial do Parana)',
        'Banco de Costa Rica': r'banco de costa rica',
        'Banco Bilbao Vizcaya': r'banco bilbao vizcaya',
    },
    'Santander': {
        'Santander': r'santander',
        'Paraiban': r'paraiban|(banco do estado da paraiba)',
        'Banco Real': 'banco real',
        'Banco Sudameris': 'banco sudameris',
        'Banco Noroeste': 'banco noroeste',
        'Getnet': 'getnet',
        'Banco ABN': 'banco abn',
        'Banco Meridional': 'banco meridional',
        'BANDEPE': 'bandepe|(banco do estado de pernambuco)',
        'Banespa': r'banespa|(banco do estado de sao paulo)',
        'Banespa': r'banespa|(banco do estado de sao paulo)',
        'Banco de Credito Hipotecario e Agricola do Estado de Sao Paulo': r'Banco de Credito Hipotecario e Agricola do Estado de Sao Paulo',
        'Banco de Credito Real de Sao Paulo': r'Banco de Credito Real de Sao Paulo',
        'Banco Comercial de Sao Paulo': r'Banco Comercial de Sao Paulo',
        'Banco Industrial de Sao Paulo': r'Banco Industrial de Sao Paulo',
        'Banco America do Sul': r'Banco America do Sul'
    },
    'Itau': {
        'Itau': r'itau',
        'Banerj': r'(\sBANERJ\s)|(banco do estado do rio de janeiro)',
        'Banco do Estado da Guanabara': r'Banco do Estado da Guanabara',
        'Banco Paulista do Comercio': r'Banco Paulista d(e|o) Comercio',
        'Banco da America': r'Banco da America',
        'Banco Alianca': r'Banco Alianca',
        'Banco Portugues do Brasil': r'Banco Portugues do Brasil',
        'Banco Uniao Comercial': r'Banco Uniao Comercial',
        'Banco Pinto Magalhaes': r'Banco Pinto Magalhaes',
        'Banco Frances e Brasileiro': r'Banco Frances e Brasileiro',
        'Bemge': 'Bemge|(Banco do Estado de Minas Gerais)',
        'Banestado': 'Banestado',
        'BEG': 'Banco do Estado de Goias',
        'Banco Imobiliario e Mercantil do Oeste Brasileiro': r'Banco Imobiliario e Mercantil do Oeste Brasileiro',
        'Banco Fiat': 'Banco Fiat',
        'BankBoston': r'BankBoston|(Bank Boston)',
        'Banco Nacional': 'Banco Nacional',
        'Itaucred': r'Itaucred',
        'Banco Bandeirantes': 'Banco Bandeirantes',
        'Banco Banorte': 'Banco Banorte',
    },
    'Banco do Brasil': {
        'Banco do Brasil': r'Banco do Brasil',
        'Banco do Estado de Santa Satarina': r'besc|(banco do estado de santa catarina)',
        'BESC Financeira': r'BESC Financeira',
        'Banco de Credito Real de Santa Catarina': r'Banco de Credito Real de Santa Catarina',
        'Banco de Desenvolvimento do Estado de Santa Catarina': r'(Banco de Desenvolvimento do Estado de Santa Catarina)|(BADESC)',
        'Banco de Credito Imobiliario de Santa Catarina': r'Banco de Credito Imobiliario de Santa Catarina',
        'Banco Comercial de Santa Catarina': r'Banco Comercial de Santa Catarina',
        'Banco Industrial de Santa Catarina': r'Banco Industrial de Santa Catarina',
        'Banco Regional de Desenvolvimento do Extremo Sul': r'(Banco Regional de Desenvolvimento do Extremo Sul)|(BRDE)',
        'BESC Financeira': r'BESC Financeira',
        'Banco do Estado do Piaui': r'(banco do estado do piaui)|(\sbep\s)',
        'Banco Nossa Caixa': r'banco nossa caixa',
        'Banco Votorantim': r'banco votorantim',
        'BV Financeira': r'BV Financeira',
        'Votorantim Corretora': r'Votorantim Corretora',
        'BV Leasing': r'BV Leasing',
        'Votorantim Asset': r'Votorantim Asset',
        'Banco Patagonia': r'banco patagonia',
        'Lloyds TSB Bank Argentina': r'Lloyds TSB Bank Argentina',
        'Banco de Credito Argentino': r'Banco de Credito Argentino',
        'EuroBank': r'(eurobank)|(euro bank)',
    },
    'Caixa Economica': {
        'Caixa Economica': r'caixa economica',
        'Banco Pan': r'banco pan',
    },
    'Btg Pactual': {
        'Btg Pactual': r'btg pactual',
        'Banco Santos': r'banco santos',
        'UBS Pactual': r'UBS Pactual',
        "Celfin Capital": r"Celfin Capital",
        "Bolsa y Renta": r"Bolsa y Renta",
        "Necton": r"Necton Investimentos",
        "Kinvo": r"Kinvo",
        "Orama": r"Orama",

    },
    'banco abc': r'banco abc',
    'pine': r'banco pine',
    'safra': r'banco safra',
    'banrisul': r'banrisul|(banco do estado do rio grande do sul)',
    'bnb': r'banco do nordeste',
    'banese': r'(banco do estado de sergipe)|banese',
    'banestes': r'(banco do estado do espirito santo)|banestes',
    'banpara': r'banpara|(banco do estado do para)',
    'brb': r'banco de brasilia',
    'china construction bank': r'(china construction bank)|bicbanco|(banco industrial)|(banco multiplo)',
    'baza': r'banco da amazonia',
    'citi': r'citibank',
    'poupex': r'poupex',
    'barclays': r'barclays',
    'bankpar': r'bankpar',
    'bbm': r'(banco bbm)|(banco bocom)',
    'bmg': r'banco bmg',
    'bnp': r'bnp paribas',
    'banco boavista': r'banco boavista',
    'brascan': r'banco brascan',
    'bva': r'banco bva',
    'daycoval': r'daycoval',
    'banco fibra': r'banco fibra',
    'sicredi': r'sicredi',
    'sofisa': r'sofisa',
    'banco original': r'banco original',
    'sicoob': r'sicoob',
    'banco cacique': r'banco cacique',
    'banco caixa geral': r'banco caixa geral',
    'banco calyon': r'banco calyon',
    'banco cargill': r'banco cargill',
    'banco citicard': r'banco citicard',
    'banco cnh': r'banco cnh',
    'credit suisse': r'credit suisse',
    'banco cruzeiro do sul': r'banco cruzeiro do sul',
    'banco da China': r'banco da china',
    'banco de lage landen': r'banco de lage landen',
    'banco de pernambuco': r'banco de pernambuco',
    'banco de tokyo': r'banco de tokyo',
    'banco dibens': r'banco dibens',
    'banco fator': r'banco fator',
    'banco fiat': r'banco fiat',
    'banco ficsa': r'banco ficsa',
    'banco gerdau': r'banco gerdau',
    'banco gmac': r'banco gmac',
    'banco guanabara': r'banco guanabara',
    'banco honda': r'banco honda',
    'banco ibi': r'banco ibi',
    'banco ibm': r'banco ibm',
    'voiter': r'(banco indusval)|voiter',
    'banco intercap': r'banco intercap',
    'banco investcred': r'banco investcred',
    'jp morgan': '(jp morgan)|(j.p. morgan)|(jpmorgan)',
    'banco john deere': r'banco john deere',
    'banco lemon': r'(banco lemon)|(lemon bank)',
    'banco luso brasileiro': r'banco luso brasileiro',
    'banco mercantil': r'banco mercantil',
    'banco merrill lynch': r'banco merrill lynch',
    'banco modal': r'banco modal',
    'banco opportunity': r'banco opportunity',
    'banco panamericano': r'banco panamericano',
    'banco paulista': r'banco paulista',
    'banco paulista': r'banco paulista',
    'banco rabobank': r'banco rabobank',
    'banco rendimento': r'banco rendimento',
    'banco rodobens': r'banco rodobens',
    'banco rural': r'banco rural',
    'banco schahin': r'banco schahin',
    'banco simples': r'banco simples',
    'banco societe generale': r'banco societe generale',
    'banco sumitomo mitsui': r'banco sumitomo mitsui',
    'banco topazio': r'banco topazio',
    'banco toyota': r'banco toyota',
    'banco triangulo': r'banco triangulo',
    'banco ubs': 'banco ubs',
    'banco volkswagen': r'banco volkswagen',
    'banco votorantim': r'banco votorantim',
    'banco vr': r'banco vr',
    'banco westlb': r'banco westlb',
    'banif': r'banif',
    'banco popular': r'banco popular',
    'bes investimento': r'bes investimento',
    'concordia banco': r'concordia banco',
    'deutsche bank': r'deutsche bank',
    'dresdner bank': r'dresdner bank',
    'banco multiplo': r'banco multiplo',
    'ing bank': r'ing bank',
}